.TH "kantor.com.web.service.KantorPrzeliczServiceLocator" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KantorPrzeliczServiceLocator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Service, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKantorPrzeliczServiceLocator\fP ()"
.br
.ti -1c
.RI "\fBKantorPrzeliczServiceLocator\fP (org\&.apache\&.axis\&.EngineConfiguration config)"
.br
.ti -1c
.RI "\fBKantorPrzeliczServiceLocator\fP (java\&.lang\&.String wsdlLoc, javax\&.xml\&.namespace\&.QName sName)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetKantorPrzeliczAddress\fP ()"
.br
.ti -1c
.RI "java\&.lang\&.String \fBgetKantorPrzeliczWSDDServiceName\fP ()"
.br
.ti -1c
.RI "void \fBsetKantorPrzeliczWSDDServiceName\fP (java\&.lang\&.String name)"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP \fBgetKantorPrzelicz\fP ()  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP \fBgetKantorPrzelicz\fP (java\&.net\&.URL portAddress)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "void \fBsetKantorPrzeliczEndpointAddress\fP (java\&.lang\&.String address)"
.br
.ti -1c
.RI "java\&.rmi\&.Remote \fBgetPort\fP (Class serviceEndpointInterface)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "java\&.rmi\&.Remote \fBgetPort\fP (javax\&.xml\&.namespace\&.QName portName, Class serviceEndpointInterface)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "namespace::QName \fBgetServiceName\fP ()"
.br
.ti -1c
.RI "java\&.util\&.Iterator \fBgetPorts\fP ()"
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (java\&.lang\&.String portName, java\&.lang\&.String address)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (javax\&.xml\&.namespace\&.QName portName, java\&.lang\&.String address)  throws javax\&.xml\&.rpc\&.ServiceException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file KantorPrzeliczServiceLocator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.KantorPrzeliczServiceLocator ()"

.PP
Definition at line 12 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.KantorPrzeliczServiceLocator (org\&.apache\&.axis\&.EngineConfigurationconfig)"

.PP
Definition at line 16 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.KantorPrzeliczServiceLocator (java\&.lang\&.StringwsdlLoc, javax\&.xml\&.namespace\&.QNamesName) throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Definition at line 20 of file KantorPrzeliczServiceLocator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getKantorPrzelicz () throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczService\fP\&.
.PP
Definition at line 42 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getKantorPrzelicz (java\&.net\&.URLportAddress) throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczService\fP\&.
.PP
Definition at line 53 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "java\&.lang\&.String kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getKantorPrzeliczAddress ()"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczService\fP\&.
.PP
Definition at line 27 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "java\&.lang\&.String kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getKantorPrzeliczWSDDServiceName ()"

.PP
Definition at line 34 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "java\&.rmi\&.Remote kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getPort (ClassserviceEndpointInterface) throws javax\&.xml\&.rpc\&.ServiceException"
For the given interface, get the stub implementation\&. If this service has no port for the given interface, then ServiceException is thrown\&. 
.PP
Definition at line 73 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "java\&.rmi\&.Remote kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getPort (javax\&.xml\&.namespace\&.QNameportName, ClassserviceEndpointInterface) throws javax\&.xml\&.rpc\&.ServiceException"
For the given interface, get the stub implementation\&. If this service has no port for the given interface, then ServiceException is thrown\&. 
.PP
Definition at line 92 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "java\&.util\&.Iterator kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getPorts ()"

.PP
Definition at line 113 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "namespace \&.QName kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.getServiceName ()"

.PP
Definition at line 107 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.setEndpointAddress (java\&.lang\&.StringportName, java\&.lang\&.Stringaddress) throws javax\&.xml\&.rpc\&.ServiceException"
Set the endpoint address for the specified port name\&. 
.PP
Definition at line 124 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.setEndpointAddress (javax\&.xml\&.namespace\&.QNameportName, java\&.lang\&.Stringaddress) throws javax\&.xml\&.rpc\&.ServiceException"
Set the endpoint address for the specified port name\&. 
.PP
Definition at line 138 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.setKantorPrzeliczEndpointAddress (java\&.lang\&.Stringaddress)"

.PP
Definition at line 64 of file KantorPrzeliczServiceLocator\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\&.setKantorPrzeliczWSDDServiceName (java\&.lang\&.Stringname)"

.PP
Definition at line 38 of file KantorPrzeliczServiceLocator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
