.TH "kantor.com.web.service.KantorPrzelicz" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KantorPrzelicz \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Remote\&.
.PP
Inherited by \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBUSDnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP (double value)"
.br
.ti -1c
.RI "double \fBEURnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP (double value)"
.br
.ti -1c
.RI "double \fBCHEnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaCHE\fP (double value)"
.br
.ti -1c
.RI "double \fBGBPnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaGBP\fP (double value)"
.br
.ti -1c
.RI "double \fBJPYnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaJPY\fP (double value)"
.br
.ti -1c
.RI "double \fBRUBnaPLN\fP (double value)"
.br
.ti -1c
.RI "double \fBPLNnaRUB\fP (double value)"
.br
.ti -1c
.RI "double[] \fBpobierz_kursy_walut\fP ()"
.br
.ti -1c
.RI "double[] \fBpobierz_kursy_walut\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBGBPnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaRUB\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBJPYnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaGBP\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaJPY\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBRUBnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBEURnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaCHE\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBCHEnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file KantorPrzelicz\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.CHEnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.CHEnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 73 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.EURnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.EURnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 47 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.GBPnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.GBPnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 99 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.JPYnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.JPYnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 125 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaCHE (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaCHE (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 86 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaEUR (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaEUR (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 60 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaGBP (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaGBP (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 112 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaJPY (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaJPY (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 138 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaRUB (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaRUB (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 164 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaUSD (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.PLNnaUSD (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 33 of file KantorPrzelicz\&.java\&.
.SS "double [] kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.pobierz_kursy_walut () throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double [] kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.pobierz_kursy_walut ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 180 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.RUBnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.RUBnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 151 of file KantorPrzelicz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.USDnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzelicz\&.USDnaPLN (doublevalue)"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\fP\&.
.PP
Definition at line 20 of file KantorPrzelicz\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
