.TH "kantor.com.web.service.KursyPokazSoapBindingStub" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KursyPokazSoapBindingStub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Stub, and \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKursyPokazSoapBindingStub\fP ()  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "\fBKursyPokazSoapBindingStub\fP (java\&.net\&.URL endpointURL, javax\&.xml\&.rpc\&.Service service)  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "\fBKursyPokazSoapBindingStub\fP (javax\&.xml\&.rpc\&.Service service)  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "double \fBEURnaPLN\fP ()  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP ()  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP ()  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP ()  throws java\&.rmi\&.RemoteException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "org\&.apache\&.axis\&.client\&.Call \fBcreateCall\fP ()  throws java\&.rmi\&.RemoteException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file KursyPokazSoapBindingStub\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.KursyPokazSoapBindingStub () throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 64 of file KursyPokazSoapBindingStub\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.KursyPokazSoapBindingStub (java\&.net\&.URLendpointURL, javax\&.xml\&.rpc\&.Serviceservice) throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 68 of file KursyPokazSoapBindingStub\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.KursyPokazSoapBindingStub (javax\&.xml\&.rpc\&.Serviceservice) throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 73 of file KursyPokazSoapBindingStub\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "org\&.apache\&.axis\&.client\&.Call kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.createCall () throws java\&.rmi\&.RemoteException\fC [protected]\fP"

.PP
Definition at line 82 of file KursyPokazSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.EURnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 115 of file KursyPokazSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.PLNnaEUR () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 149 of file KursyPokazSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.PLNnaUSD () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 183 of file KursyPokazSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\&.USDnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 217 of file KursyPokazSoapBindingStub\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
