.TH "kantor.com.web.service.KursyPokazProxy" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KursyPokazProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKursyPokazProxy\fP ()"
.br
.ti -1c
.RI "\fBKursyPokazProxy\fP (String endpoint)"
.br
.ti -1c
.RI "String \fBgetEndpoint\fP ()"
.br
.ti -1c
.RI "void \fBsetEndpoint\fP (String endpoint)"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP \fBgetKursyPokaz\fP ()"
.br
.ti -1c
.RI "double \fBEURnaPLN\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP ()  throws java\&.rmi\&.RemoteException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file KursyPokazProxy\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.KursyPokazProxy ()"

.PP
Definition at line 7 of file KursyPokazProxy\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.KursyPokazProxy (Stringendpoint)"

.PP
Definition at line 11 of file KursyPokazProxy\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.EURnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 47 of file KursyPokazProxy\&.java\&.
.SS "String kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.getEndpoint ()"

.PP
Definition at line 30 of file KursyPokazProxy\&.java\&.
.SS "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.getKursyPokaz ()"

.PP
Definition at line 41 of file KursyPokazProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.PLNnaEUR () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 53 of file KursyPokazProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.PLNnaUSD () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 59 of file KursyPokazProxy\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.setEndpoint (Stringendpoint)"

.PP
Definition at line 34 of file KursyPokazProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokazProxy\&.USDnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP\&.
.PP
Definition at line 65 of file KursyPokazProxy\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
