.TH "kantor.com.web.service.HttpDownloadUtility" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.HttpDownloadUtility \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdownloadFile\fP (String fileURL, String saveDir)  throws IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file HttpDownloadUtility\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void kantor\&.com\&.web\&.service\&.HttpDownloadUtility\&.downloadFile (StringfileURL, StringsaveDir) throws IOException\fC [static]\fP"
Downloads a file from a URL 
.PP
\fBParameters:\fP
.RS 4
\fIfileURL\fP HTTP URL of the file to be downloaded 
.br
\fIsaveDir\fP path of the directory to save the file 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP

.PP
Definition at line 21 of file HttpDownloadUtility\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
