.TH "kantor.com.web.service.KursyPokaz" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KursyPokaz \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Remote\&.
.PP
Inherited by \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBEURnaPLN\fP ()"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP ()"
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP ()"
.br
.ti -1c
.RI "double \fBEURnaPLN\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP ()  throws java\&.rmi\&.RemoteException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file KursyPokaz\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.EURnaPLN ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.PP
Definition at line 4 of file KursyPokaz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.EURnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.PLNnaEUR () throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.PLNnaUSD ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.PP
Definition at line 8 of file KursyPokaz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.PLNnaUSD () throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.USDnaPLN ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.
.PP
Definition at line 12 of file KursyPokaz\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KursyPokaz\&.USDnaPLN () throws java\&.rmi\&.RemoteException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazSoapBindingStub\fP, and \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
