.TH "C:/Users/kuska/Desktop/Michalik/KW/KantorWSClient/src/kantor/com/web/service/KursyPokazProxy.java" 3 "Thu Jan 14 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kuska/Desktop/Michalik/KW/KantorWSClient/src/kantor/com/web/service/KursyPokazProxy.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkantor\&.com\&.web\&.service\&.KursyPokazProxy\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBkantor\&.com\&.web\&.service\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
