.TH "C:/Users/kuska/Desktop/Michalik/KW/KantorWS/src Directory Reference" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kuska/Desktop/Michalik/KW/KantorWS/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBkantor\fP"
.br
.in -1c
