.TH "kantor.com.web.service.KursyPokazService" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KursyPokazService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Service\&.
.PP
Inherited by \fBkantor\&.com\&.web\&.service\&.KursyPokazServiceLocator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java\&.lang\&.String \fBgetKursyPokazAddress\fP ()"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP \fBgetKursyPokaz\fP ()  throws javax\&.xml\&.rpc\&.ServiceException"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP \fBgetKursyPokaz\fP (java\&.net\&.URL portAddress)  throws javax\&.xml\&.rpc\&.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file KursyPokazService\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP kantor\&.com\&.web\&.service\&.KursyPokazService\&.getKursyPokaz () throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazServiceLocator\fP\&.
.SS "\fBkantor\&.com\&.web\&.service\&.KursyPokaz\fP kantor\&.com\&.web\&.service\&.KursyPokazService\&.getKursyPokaz (java\&.net\&.URLportAddress) throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazServiceLocator\fP\&.
.SS "java\&.lang\&.String kantor\&.com\&.web\&.service\&.KursyPokazService\&.getKursyPokazAddress ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KursyPokazServiceLocator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KalkulatorWymianyWalut from the source code\&.
