.TH "kantor.com.web.service.KantorPrzeliczService" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KantorPrzeliczService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Service\&.
.PP
Inherited by \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java\&.lang\&.String \fBgetKantorPrzeliczAddress\fP ()"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP \fBgetKantorPrzelicz\fP ()  throws javax\&.xml\&.rpc\&.ServiceException"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP \fBgetKantorPrzelicz\fP (java\&.net\&.URL portAddress)  throws javax\&.xml\&.rpc\&.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file KantorPrzeliczService\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP kantor\&.com\&.web\&.service\&.KantorPrzeliczService\&.getKantorPrzelicz () throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\fP\&.
.SS "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP kantor\&.com\&.web\&.service\&.KantorPrzeliczService\&.getKantorPrzelicz (java\&.net\&.URLportAddress) throws javax\&.xml\&.rpc\&.ServiceException"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\fP\&.
.SS "java\&.lang\&.String kantor\&.com\&.web\&.service\&.KantorPrzeliczService\&.getKantorPrzeliczAddress ()"

.PP
Implemented in \fBkantor\&.com\&.web\&.service\&.KantorPrzeliczServiceLocator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KalkulatorWymianyWalut from the source code\&.
