.TH "kantor.com.web.service.KantorPrzeliczSoapBindingStub" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KantorPrzeliczSoapBindingStub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Stub, and \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKantorPrzeliczSoapBindingStub\fP ()  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "\fBKantorPrzeliczSoapBindingStub\fP (java\&.net\&.URL endpointURL, javax\&.xml\&.rpc\&.Service service)  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "\fBKantorPrzeliczSoapBindingStub\fP (javax\&.xml\&.rpc\&.Service service)  throws org\&.apache\&.axis\&.AxisFault "
.br
.ti -1c
.RI "double[] \fBpobierz_kursy_walut\fP ()  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBGBPnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaRUB\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBJPYnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaGBP\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaJPY\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBRUBnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBEURnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBPLNnaCHE\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.ti -1c
.RI "double \fBCHEnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "org\&.apache\&.axis\&.client\&.Call \fBcreateCall\fP ()  throws java\&.rmi\&.RemoteException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.KantorPrzeliczSoapBindingStub () throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 175 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.KantorPrzeliczSoapBindingStub (java\&.net\&.URLendpointURL, javax\&.xml\&.rpc\&.Serviceservice) throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 179 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.KantorPrzeliczSoapBindingStub (javax\&.xml\&.rpc\&.Serviceservice) throws org\&.apache\&.axis\&.AxisFault"

.PP
Definition at line 184 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.CHEnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 634 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "org\&.apache\&.axis\&.client\&.Call kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.createCall () throws java\&.rmi\&.RemoteException\fC [protected]\fP"

.PP
Definition at line 193 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.EURnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 532 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.GBPnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 260 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.JPYnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 328 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaCHE (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 600 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaEUR (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 566 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaGBP (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 362 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaJPY (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 396 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaRUB (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 294 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.PLNnaUSD (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 498 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double [] kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.pobierz_kursy_walut () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 226 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.RUBnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 430 of file KantorPrzeliczSoapBindingStub\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczSoapBindingStub\&.USDnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 464 of file KantorPrzeliczSoapBindingStub\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KalkulatorWymianyWalut from the source code\&.
