.TH "kantor.com.web.service.KantorPrzeliczProxy" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kantor.com.web.service.KantorPrzeliczProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKantorPrzeliczProxy\fP ()"
.br
.ti -1c
.RI "\fBKantorPrzeliczProxy\fP (String endpoint)"
.br
.ti -1c
.RI "String \fBgetEndpoint\fP ()"
.br
.ti -1c
.RI "void \fBsetEndpoint\fP (String endpoint)"
.br
.ti -1c
.RI "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP \fBgetKantorPrzelicz\fP ()"
.br
.ti -1c
.RI "double[] \fBpobierz_kursy_walut\fP ()  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBGBPnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaRUB\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBJPYnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaGBP\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaJPY\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBRUBnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBUSDnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaUSD\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBEURnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaEUR\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBPLNnaCHE\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.ti -1c
.RI "double \fBCHEnaPLN\fP (double value)  throws java\&.rmi\&.RemoteException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file KantorPrzeliczProxy\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.KantorPrzeliczProxy ()"

.PP
Definition at line 7 of file KantorPrzeliczProxy\&.java\&.
.SS "kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.KantorPrzeliczProxy (Stringendpoint)"

.PP
Definition at line 11 of file KantorPrzeliczProxy\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.CHEnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 119 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.EURnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 101 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.GBPnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 53 of file KantorPrzeliczProxy\&.java\&.
.SS "String kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.getEndpoint ()"

.PP
Definition at line 30 of file KantorPrzeliczProxy\&.java\&.
.SS "\fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.getKantorPrzelicz ()"

.PP
Definition at line 41 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.JPYnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 65 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaCHE (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 113 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaEUR (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 107 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaGBP (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 71 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaJPY (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 77 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaRUB (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 59 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.PLNnaUSD (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 95 of file KantorPrzeliczProxy\&.java\&.
.SS "double [] kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.pobierz_kursy_walut () throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 47 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.RUBnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 83 of file KantorPrzeliczProxy\&.java\&.
.SS "void kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.setEndpoint (Stringendpoint)"

.PP
Definition at line 34 of file KantorPrzeliczProxy\&.java\&.
.SS "double kantor\&.com\&.web\&.service\&.KantorPrzeliczProxy\&.USDnaPLN (doublevalue) throws java\&.rmi\&.RemoteException"

.PP
Implements \fBkantor\&.com\&.web\&.service\&.KantorPrzelicz\fP\&.
.PP
Definition at line 89 of file KantorPrzeliczProxy\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KalkulatorWymianyWalut from the source code\&.
