.TH "C:/Users/kuska/Desktop/Michalik/KW/html/search/namespaces_0.js" 3 "Thu Jan 14 2016" "KalkulatorWymianyWalut" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kuska/Desktop/Michalik/KW/html/search/namespaces_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['com',['com',['\&.\&./namespacekantor_1_1com\&.html',1,'kantor']]],
  ['kantor',['kantor',['\&.\&./namespacekantor\&.html',1,'']]],
  ['service',['service',['\&.\&./namespacekantor_1_1com_1_1web_1_1service\&.html',1,'kantor::com::web']]],
  ['web',['web',['\&.\&./namespacekantor_1_1com_1_1web\&.html',1,'kantor::com']]]
]
.fi
.PP
Definition at line 1 of file namespaces_0\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for KalkulatorWymianyWalut from the source code\&.
